### ISSUE TITLE
"Fatal Error in Wish" Crash on 32-bit Windows 10

### ISSUE THREAD

**Issue by pvn44** [hvxl/otmonitor#16]
Roughly once every 2 days I get this seemingly random crash where it presents a pop-up window with the text "Fatal Error in Wish". Once this window is shown, no data is written to the logfile anymore, and the screen is not updated any longer.
When you close this pop-up window, otmonitor quits. No further info is shown. The OTGW itself keeps running fine.

Tested with version 5.0 of both OGTW and otmonitor. The OGTW is about two weeks old now.
32-bit Windows 10 on a single core laptop with 2 GB main memory.
Using FTDI serial-to-USB cable.

**Comment by hvxl** [comment]
Are you running OTmonitor with a GUI? It sounds like you are. I suspect the problem may be that memory gets fragmented after a while and the process isn't able to obtain a chunk large enough for its needs at some point. In OOM (out of memory) situations, the program doesn't have many other options than to terminate.

The part that uses the largest chunk of memory when running OTmonitor in GUI-mode is the log window. It currently keeps 15000 lines of history, as defined by the `logsize` variable in otmonitor.tcl. Can you try to reduce that to 5000 and see if it then runs longer than 2 days? I won't guarantee that it will run indefinitely with a smaller log size, but hopefully it lasts significantly longer.

**Comment by hvxl** [comment]
No response for over a year. Closing.
