### ISSUE TITLE
INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by timoline** [hvxl/otmonitor#17]
it lookslike it works perfect, I only see this error in the (web) logging
(version 51)

header accept-encoding: gzip {} deflate {}
header accept-language: en-us {} en {q 0.9} nl {q 0.8}
accept type: text/html application/xhtml+xml image/avif image/webp image/apng application/xml application/signed-exchange */*
accept charset: 
accept encoding: gzip deflate
accept language: en-us en nl
accept transfercoding: 
errorinfo: key "temperature" not known in dictionary
    while executing
"dict get $xlate $n"
    ("foreach" body line 2)
    invoked from within
"foreach n $cfg(datalog,itemlist) {
append # [subst {<option value="$n">[dict get $xlate $n]</option>
}]
 }"
    ("uplevel" body line 118)
    invoked from within
"uplevel 1 "set # {}; $script; set #""
    (procedure "template" line 17)
    invoked from within
"template $body"
    (procedure "::wibble::zone::templatefile" line 8)
    invoked from within
"{*}$command $state"
    (procedure "getresponse" line 38)
    invoked from within
"getresponse $request"
*** INTERNAL SERVER ERROR (END #5) ***

**Comment by hvxl** [comment]
The error indicates you have an entry called "temperature" in the datalog itemlist in your configuration file. This is not a recognized item, although it may have been in the past. In any case, the program should handle such a situation more elegantly.

**Comment by hvxl** [comment]
Fixed by commit d56bf02

**Comment by timoline** [comment]
thx
