### ISSUE TITLE
MQTT actions not processed after commit 888a1d2 (Return the result of commands via MQTT if the caller specified a response)

### ISSUE THREAD

**Issue by SenH** [hvxl/otmonitor#23]
My broker is Mosquito (MQTTv3.1.1 - protocol 4). The actions are not received in the `mqttaction` procedure from commit 888a1d2. The previous commit 4cb83640bd5e7bd1b8650e47029d18a9a430168c is OK.

This patch seems to fix my issue (but it will break MQTTv5):
````
-proc mqttaction {topic data retain props args} {
+proc mqttaction {topic data retain {props {}}} {
````

**Comment by dhannema** [comment]
@SenH Thanks, this indeed fixes the MQTT bug for now 👍

**Comment by hvxl** [comment]
> This patch seems to fix my issue (but it will break MQTTv5):
> 
That patch is perfectly fine for MQTTv5 as well. I just like to be prepared for possible future additions of more arguments.
