### ISSUE TITLE
MQTT Messages are ignored 

### ISSUE THREAD

**Issue by alpar-t** [hvxl/otmonitor#24]
Hey,

Thanks for this great tool! 

I upgraded from 6.1 to 6.5 and mqtt messages were being ignored. 
In particular I have a process that sends something like `{ value:  32}` to `actions/otmonitor/ctrlsetpt` ant all I could see in the logs was  the setpoint being written to 0. I tried both with protocol version 3.1.1 and 5. 

Reverting back to 6.1 fixed it.

**Comment by alpar-t** [comment]
Also I've seen no messages of this kind in the log, but I'm seeing them with 6.1:
```
19:34:13.098735	R80380000	Read-Data 	DHW setpoint: 0.00
19:34:13.229124	B40383000	Read-Ack  	DHW setpoint: 48.00
19:34:13.296601	Command (via MQTT): CH=1
19:34:13.315463	CH: 1
19:34:13.337758	Command (via MQTT): MM=80
19:34:13.339090	Command (via MQTT): CS=32.72
19:34:13.341110	Command (via MQTT): SW=48
19:34:13.344114	Command (via MQTT): SH=38
19:34:13.346434	Command (via MQTT): HW=0
19:34:13.364505	MM: 80
19:34:13.421718	CS: 32.72
19:34:13.422809	SW: 48.00
19:34:13.424301	SH: 38.00
19:34:13.425875	HW: 0
19:34:14.122458	R80000100	Read-Data 	Status: 00000001 00000000
19:34:14.245020	B4000010A	Read-Ack  	Status: 00000001 00001010
19:34:15.157585	R80190000	Read-Data 	Boiler water temperature: 0.00
19:34:15.281662	B40192019	Read-Ack  	Boiler water temperature: 32.10
19:34:16.194459	R100120B9	Write-Data	Control setpoint: 32.72
19:34:16.302140	BD00120B9	Write-Ack 	Control setpoint: 32.72
19:34:17.225858	R10383000	Write-Data	DHW setpoint: 48.00
19:34:17.363837	BD0383000	Write-Ack 	DHW setpoint: 48.00
19:34:18.258435	R10392600	Write-Data	Max CH water setpoint: 38.00
19:34:18.386090	BD0392600	Write-Ack 	Max CH water setpoint: 38.00
```

**Comment by hvxl** [comment]
This sounds like it may be a duplicate of issue #23.

**Comment by hvxl** [comment]
In case you are not aware: Binaries for each commit are automatically built via github actions. You can find them by clicking the build you are interested in on the [actions tab](https://github.com/hvxl/otmonitor/actions).

**Comment by alpar-t** [comment]
Indeed, the last binary built from there works like a charm. Thanks !
