### ISSUE TITLE
content-type not included headers for webserver

### ISSUE THREAD

**Issue by basnijholt** [hvxl/otmonitor#8]
I have made a [Home Assistant add-on](https://github.com/basnijholt/addon-otmonitor), where I serve `otmonitor` in a Docker image and reverse proxy using Nginx.

In order to make it work, I needed to force add ([this](https://github.com/basnijholt/addon-otmonitor/blob/master/otmonitor/rootfs/etc/nginx/servers/ingress.conf#L11)) the content type.

See the error in the console:
![image](https://user-images.githubusercontent.com/6897215/74223413-eea87e00-4cb6-11ea-9645-2758786bd5d8.png)

The solution is to add the content-type in the headers.

**Comment by hvxl** [comment]
I don't use Home Assistant. Can you report if https://github.com/hvxl/otmonitor/commit/4fbd14cae9b38493b5e09e182ff22615c7574fd0 fixes the issue?

**Comment by basnijholt** [comment]
Great! Thanks for the quick fix.

Unfortunately, I do not have an easy test environment available. I would have to upload the binaries somewhere for a Raspberry Pi to be able to test it, and I do not know how to compile TCL code.

If you would be able to provide the Linux-armhf version (or some directions/instructions), it would be easy to verify if it works 😄

**Comment by hvxl** [comment]
Such instructions are available on the [otgw web site](http://otgw.tclcode.com/otmonsrc.html).

**Comment by hvxl** [comment]
Fixed in OTmonitor 4.4.
